Add ability to delete resources

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -24,11 +24,6 @@ MYDIR=$( dirname "$(readlink -f "$0")" )
 source "$MYDIR/variables.sh"
 source "$MYDIR/utils.sh"
 
-# pretty printing of code.
-e=$(printf "\e") 
-readonly CODE_S="$e[32m"
-readonly CODE_E="$e[0m"
-
 #------------------------------------------------------------------------------------
 # showhelp - give some info about the service. SERVICENAME and IMAGENAME are provided by variables.sh.
 
@@ -47,6 +42,9 @@ SYNOPSIS
    ${CODE_S}${SERVICENAME} create RESOURCE_FILE${CODE_E}
       Creates resources specified in RESOURCE_FILE.
    
+   ${CODE_S}${SERVICENAME} delete RESOURCE_FILE${CODE_E}
+      Deletes resources specified in RESOURCE_FILE.
+   
 DESCRIPTION
    Helpers for creating AWS resources. Built from ${IMAGENAME}.
    
@@ -57,6 +55,14 @@ EOF
 # Run a command in a temporary container. 
 
 function dockerrun {
+   local RVAL=0
+   docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@"
+   RVAL=$?
+   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
+   [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
+}
+
+function dockerrunwithvolumes {
    local RVAL=0
    docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" $1 "${IMAGENAME}" "$2"
    RVAL=$?
@@ -107,7 +113,7 @@ function main {
          enter)
             shift
             COMMANDOPTS=("-it")
-            dockerrun "" /bin/bash "$@"
+            dockerrun /bin/bash "$@"
             ;;
          
          updatestart)
@@ -124,13 +130,19 @@ function main {
          configure)
             shift
             [ "$#" -eq 3 ] || die "dresource configure USERNAME AWS_ACCESS_KEY AWS_SECRET_KEY"
-            dockerrun "" "configure $1 $2 $3"
+            dockerrun configure $1 $2 $3
             ;;
             
          create)
             shift
-             [ "$#" -eq 1 ] || die "dresource create RESOURCE_FILE"
-            dockerrun "-v $1:/config/createfile" "create"
+            [ "$#" -eq 1 ] || die "dresource create RESOURCE_FILE"
+            dockerrunwithvolumes "-v $1:/config/resourceFile" "create"
+           ;;
+           
+         delete)
+            shift
+            [ "$#" -eq 1 ] || die "dresource delete RESOURCE_FILE"
+            dockerrunwithvolumes "-v $1:/config/resourceFile" "delete"
            ;;
             
          #--- unrecognised commands
