Update to drunner 2

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -55,25 +55,6 @@ EOF
 }
 
 #------------------------------------------------------------------------------------
-# Run a command in a temporary container. 
-
-function dockerrun {
-   local RVAL=0
-   docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@"
-   RVAL=$?
-   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
-   [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
-}
-
-function dockerrunwithvolumes {
-   local RVAL=0
-   docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" $1 "${IMAGENAME}" $2
-   RVAL=$?
-   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
-   [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
-}
-
-#------------------------------------------------------------------------------------
 # The main function. We can add any commands we'd like here!
 
 function main {
@@ -104,18 +85,26 @@ function main {
          #--- custom commands
 
          configure)
-            [ "$#" -eq 3 ] || die "dresource configure USERNAME AWS_ACCESS_KEY AWS_SECRET_KEY"
-            dockerrun configure $1 $2 $3
+            [ ! -z "${USERNAME:-}" ] || die "Username not found, please run ${CODE_S}USERNAME=? AWS_ACCESS_KEY=? AWS_SECRET_KEY=? ${SERVICENAME} configure${CODE_E}"
+            [ ! -z "${AWS_ACCESS_KEY:-}" ] || die "AWS Access Key not found, please run ${CODE_S}USERNAME=? AWS_ACCESS_KEY=? AWS_SECRET_KEY=? ${SERVICENAME} configure${CODE_E}"
+            [ ! -z "${AWS_SECRET_KEY:-}" ] || die "AWS Secret Key not found, please run ${CODE_S}USERNAME=? AWS_ACCESS_KEY=? AWS_SECRET_KEY=? ${SERVICENAME} configure${CODE_E}"
+
+            save_environment "USERNAME" "${USERNAME}"
+            save_environment "AWS_ACCESS_KEY" "${AWS_ACCESS_KEY}"
+            save_environment "AWS_SECRET_KEY" "${AWS_SECRET_KEY}"
             ;;
             
          create)
             [ "$#" -eq 1 ] || die "dresource create RESOURCE_FILE"
-            dockerrunwithvolumes "-v $1:/resources/resourceConfigFile" "run createResources.yml"
+            FILE=$(realpath $1)
+            RESOURCE_FILE="$FILE" docker-compose -p "${SERVICENAME}" run --rm -T "--user=\"$(id -u):$(id -g)\"" \
+                  dresource bash -c "ansible-playbook -i /ansible/inventory /ansible/createResources.yml"
            ;;
            
          delete)
             [ "$#" -eq 1 ] || die "dresource delete RESOURCE_FILE"
-            dockerrunwithvolumes "-v $1:/resources/resourceConfigFile" "run deleteResources.yml"
+            RESOURCE_FILE="${1}" docker-compose -p "${SERVICENAME}" run --rm -T "--user=\"$(id -u):$(id -g)\"" \
+                  dresource bash -c "ansible-playbook -i /ansible/inventory /ansible/deleteResources.yml"
            ;;
             
          #--- unrecognised commands
